name: Custom Action with Email Step

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3002175@ds.study.iitm.ac.in  # Step with your email
        run: echo "Action triggered successfully!"
